"""Image generation API clients."""

import asyncio
import base64
import logging
import math
import os
from pathlib import Path

import aiohttp
import httpx

try:
    from google import genai
    from google.genai import types

    GENAI_AVAILABLE = True
except ImportError:
    genai = None
    types = None
    GENAI_AVAILABLE = False
from openai import AsyncOpenAI

logger = logging.getLogger(__name__)


def _image_result(response):
    """Decode one bounded inline result; safe tool calls never fetch image URLs."""
    if len(response.data or []) != 1 or not response.data[0].b64_json:
        raise ValueError("Images API must return exactly one inline image")
    encoded = response.data[0].b64_json
    if len(encoded) > 12 * 1024 * 1024:
        raise ValueError("Image response exceeds the bounded artifact limit")
    data = base64.b64decode(encoded, validate=True)
    if len(data) > 8 * 1024 * 1024:
        raise ValueError("Image response exceeds the bounded artifact limit")
    usage = getattr(response, "usage", None)
    return {
        "data": data,
        "request_id": getattr(response, "_request_id", None),
        "usage": usage.model_dump() if usage is not None else None,
    }


class ImagenClient:
    """Client for Google's image generation via Gemini API."""

    api_name = "imagen"
    COST_PER_IMAGE = 0.035

    def __init__(self, *, vertexai=None, single_attempt=False):
        self.api_key = os.getenv("GOOGLE_API_KEY")
        self.configured = bool(self.api_key and self.api_key.strip() and GENAI_AVAILABLE)
        self.client = None
        if self.configured and genai:
            try:
                # None preserves the existing library/environment behavior.
                # The safe mounted adapter explicitly selects Vertex API-key mode.
                options = {} if vertexai is None else {"vertexai": vertexai}
                if single_attempt:
                    # genai's aiohttp path retries some connection errors even
                    # with attempts=1. Use its supported HTTPX transport option;
                    # the SDK owns/closes this transport with its async client.
                    options["http_options"] = types.HttpOptions(
                        timeout=None,
                        retry_options=types.HttpRetryOptions(attempts=1),
                        async_client_args={"transport": httpx.AsyncHTTPTransport(retries=0)},
                    )
                self.client = genai.Client(api_key=self.api_key, **options)
            except Exception as e:
                logger.warning(f"Failed to initialize Google client: {e}")
                self.configured = False
                self.client = None

    async def generate(
        self,
        prompt: str,
        output_path: Path,
        params: dict | None = None,
    ) -> tuple[str, float]:
        """Generate image using Google Gemini API.

        Uses Imagen 4 for generation.

        Args:
            prompt: Text description of the image to generate
            output_path: Path where the generated image should be saved
            params: Optional parameters

        Returns:
            Tuple of (image_url, estimated_cost)

        Raises:
            ValueError: If API key not configured or service unavailable
        """
        if not self.configured or not self.client:
            raise ValueError("Google API key not configured. Please set GOOGLE_API_KEY environment variable.")

        output_path = output_path.expanduser()
        logger.info(f"Generating Google image with prompt: {prompt[:100]}...")

        try:
            loop = asyncio.get_event_loop()
            response = await loop.run_in_executor(None, self._generate_sync, prompt)

            if not response.generated_images:
                raise ValueError("No images generated by Google API")

            generated_image = response.generated_images[0]

            output_path.parent.mkdir(parents=True, exist_ok=True)

            image_data = generated_image.image.image_bytes
            output_path.write_bytes(image_data)

            logger.info(f"Image saved to: {output_path}")
            logger.info(f"Estimated cost: ${self.COST_PER_IMAGE:.3f}")

            return f"file://{output_path}", self.COST_PER_IMAGE

        except Exception as e:
            logger.error(f"Failed to generate image with Google: {e}")
            raise

    def _generate_sync(self, prompt: str):
        """Synchronous helper for generating images."""
        if not self.client or not types:
            raise RuntimeError("Google API client not initialized")

        return self.client.models.generate_images(
            model="imagen-4.0-generate-001",
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="1:1",
                safety_filter_level=types.SafetyFilterLevel.BLOCK_LOW_AND_ABOVE,
                include_rai_reason=False,
            ),
        )

    async def check_availability(self) -> bool:
        """Check if Google API is configured.

        Returns:
            True if API key is configured, False otherwise
        """
        if not self.configured:
            logger.warning("Google API not configured - missing GOOGLE_API_KEY")
            return False

        if not self.client:
            return False

        try:
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(None, self.client.models.list)
            logger.info("Google Imagen API is available and configured.")
            return True
        except Exception as e:
            logger.warning(f"Google API key configured but API check failed: {e}")
            return False

    async def generate_bytes(
        self, *, prompt, model, action, images, size, quality, background, timeout
    ):
        """Explicit single-attempt generation for the workspace tool, without writes.

        The library's existing synchronous/executor API remains unchanged. This
        path uses the SDK's async transport so cancellation does not abandon an
        executor thread that can keep submitting or saving an image.
        """
        if not self.configured or not self.client or types is None:
            raise ValueError("Google image backend is not configured")
        if (
            action != "generate"
            or images
            or (size, quality, background) != ("1024x1024", "standard", "opaque")
        ):
            raise ValueError("Imagen adapter supports square standard generation only")
        response = await self.client.aio.models.generate_images(
            model=model,
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="1:1",
                image_size="1K",
                output_mime_type="image/png",
                safety_filter_level=types.SafetyFilterLevel.BLOCK_LOW_AND_ABOVE,
                include_rai_reason=False,
                http_options=types.HttpOptions(
                    timeout=math.ceil(timeout * 1000) if timeout is not None else None,
                    retry_options=types.HttpRetryOptions(attempts=1),
                ),
            ),
        )
        if len(response.generated_images or []) != 1:
            raise ValueError("Imagen must return exactly one image")
        data = response.generated_images[0].image.image_bytes
        if not isinstance(data, bytes) or len(data) > 8 * 1024 * 1024:
            raise ValueError("Imagen returned missing or oversized image bytes")
        return {"data": data, "request_id": None, "usage": None}


class DalleClient:
    """Client for OpenAI DALL-E API."""

    api_name = "dalle"

    COST_PER_IMAGE = {
        "standard": 0.040,
        "hd": 0.080,
    }

    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY")
        self.configured = bool(self.api_key)
        self.client = None
        if self.configured:
            self.client = AsyncOpenAI(api_key=self.api_key)

    async def generate(
        self,
        prompt: str,
        output_path: Path,
        params: dict | None = None,
    ) -> tuple[str, float]:
        """Generate an image using DALL-E 3.

        Args:
            prompt: Text description of the image to generate
            output_path: Path where the generated image should be saved
            params: Optional parameters (quality, style, etc.)

        Returns:
            Tuple of (image_url, estimated_cost)

        Raises:
            ValueError: If API key not configured
            Exception: For API or download errors
        """
        if not self.configured or not self.client:
            raise ValueError("OpenAI API key not configured. Please set OPENAI_API_KEY environment variable.")

        output_path = output_path.expanduser()
        params = params or {}
        quality = params.get("quality", "standard")
        style = params.get("style", "natural")
        size = params.get("size", "1024x1024")

        logger.info(f"Generating DALL-E image with prompt: {prompt[:100]}...")
        logger.info(f"Parameters: quality={quality}, style={style}, size={size}")

        try:
            response = await self.client.images.generate(
                model="dall-e-3",
                prompt=prompt,
                size=size,
                quality=quality,
                style=style,
                n=1,
            )

            image_url = response.data[0].url if response.data else None
            if not image_url:
                raise ValueError("No image URL returned from DALL-E API")

            logger.info(f"Image generated successfully. Downloading from: {image_url[:80]}...")

            await self._download_image(image_url, output_path)

            cost = self.COST_PER_IMAGE.get(quality, self.COST_PER_IMAGE["standard"])

            logger.info(f"Image saved to: {output_path}")
            logger.info(f"Estimated cost: ${cost:.3f}")

            return image_url, cost

        except Exception as e:
            logger.error(f"Failed to generate image with DALL-E: {e}")
            raise

    async def _download_image(self, url: str, output_path: Path) -> None:
        """Download image from URL and save to path.

        Args:
            url: URL of the image to download
            output_path: Path where the image should be saved
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        async with (
            aiohttp.ClientSession() as session,
            session.get(url) as response,
        ):
            response.raise_for_status()
            content = await response.read()
            output_path.write_bytes(content)

    async def check_availability(self) -> bool:
        """Check if DALL-E API is configured.

        Returns:
            True if API key is configured, False otherwise
        """
        if not self.configured:
            logger.warning("DALL-E API not configured - missing OPENAI_API_KEY")
            return False

        return True

    async def generate_bytes(
        self, *, prompt, model, action, images, size, quality, background, timeout
    ):
        """Single inline image, no URL fetch, filesystem write, retry or fallback."""
        if not self.configured or self.client is None:
            raise ValueError("OpenAI image backend is not configured")
        if action != "generate" or images or background != "opaque":
            raise ValueError("DALL-E adapter supports opaque generation only")
        response = await self.client.with_options(
            max_retries=0, timeout=timeout
        ).images.generate(
            model=model,
            prompt=prompt,
            size=size,
            quality=quality,
            style="natural",
            n=1,
            response_format="b64_json",
        )
        return _image_result(response)


class GptImageClient:
    """Client for OpenAI GPT-Image-1 API."""

    api_name = "gptimage"

    COST_PER_IMAGE = {
        "low": 0.020,
        "medium": 0.040,
        "high": 0.080,
        "auto": 0.040,
    }

    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY")
        self.configured = bool(self.api_key)
        self.client = None
        if self.configured:
            self.client = AsyncOpenAI(api_key=self.api_key)

    async def generate(
        self,
        prompt: str,
        output_path: Path,
        params: dict | None = None,
    ) -> tuple[str, float]:
        """Generate an image using GPT-Image-1.

        Args:
            prompt: Text description of the image to generate
            output_path: Path where the generated image should be saved
            params: Optional parameters (quality, size)

        Returns:
            Tuple of (image_url, estimated_cost)

        Raises:
            ValueError: If API key not configured
            Exception: For API or download errors
        """
        if not self.configured or not self.client:
            raise ValueError("OpenAI API key not configured. Please set OPENAI_API_KEY environment variable.")

        output_path = output_path.expanduser()
        params = params or {}
        quality_param = params.get("quality", "standard")
        quality = {"standard": "medium", "hd": "high"}.get(quality_param, quality_param)
        size = params.get("size", "1024x1024")

        logger.info(f"Generating GPT-Image-1 image with prompt: {prompt[:100]}...")
        logger.info(f"Parameters: quality={quality}, size={size}")

        try:
            response = await self.client.images.generate(
                model="gpt-image-1",
                prompt=prompt,
                size=size,
                quality=quality,
                n=1,
            )

            if not response.data or len(response.data) == 0:
                raise ValueError("No image data returned from GPT-Image-1 API")

            b64_data = response.data[0].b64_json
            if not b64_data:
                raise ValueError("No base64 image data in GPT-Image-1 response")

            logger.info("Image generated successfully. Decoding base64 data...")

            image_bytes = base64.b64decode(b64_data)

            output_path.parent.mkdir(parents=True, exist_ok=True)

            output_path.write_bytes(image_bytes)

            cost = self.COST_PER_IMAGE.get(quality if quality else "auto", self.COST_PER_IMAGE["auto"])

            logger.info(f"Image saved to: {output_path}")
            logger.info(f"Estimated cost: ${cost:.3f}")

            return f"file://{output_path}", cost

        except Exception as e:
            logger.error(f"Failed to generate image with GPT-Image-1: {e}")
            raise

    async def check_availability(self) -> bool:
        """Check if GPT-Image-1 API is configured.

        Returns:
            True if API key is configured, False otherwise
        """
        if not self.configured:
            logger.warning("GPT-Image-1 API not configured - missing OPENAI_API_KEY")
            return False

        return True

    async def generate_bytes(
        self, *, prompt, model, action, images, size, quality, background, timeout
    ):
        """Generate or edit one image using this selected client's credentials."""
        if not self.configured or self.client is None:
            raise ValueError("OpenAI image backend is not configured")
        if action not in {"generate", "edit"} or (action == "edit") != bool(images):
            raise ValueError(
                "Edit requires image inputs; generate does not accept them"
            )
        client = self.client.with_options(max_retries=0, timeout=timeout)
        params = {
            "model": model,
            "prompt": prompt,
            "size": size,
            "quality": quality,
            "background": background,
            "output_format": "png",
            "n": 1,
        }
        if action == "edit":
            response = await client.images.edit(
                **params,
                image=[(row["name"], row["data"], row["mimeType"]) for row in images],
            )
        else:
            response = await client.images.generate(**params)
        return _image_result(response)
